version: 2

models:
    - name: ORDERS
      description: "This is Orders dbt model"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null